name: Auto Merge

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  merge-me:
    name: Auto-merge dependency updates
    runs-on: ubuntu-latest

    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: arturoherrero/merge-me-action@d6ed1db
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
