name: Build

on: [push]

jobs:
  test:
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install libxslt and libxml2
        run: sudo apt-get install libxslt-dev libxml2-dev

      - name: Set up Ruby
        uses: actions/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake
